@startuml

participant ":JeuDeDes"
participant "joueurs: Map<String, Joueur>"

-> ":JeuDeDes" : redemarrerJeu()

note right of ":JeuDeDes"
    selon Controleur 
    (JeuDeDés est 
    l'objet racine)
end note

":JeuDeDes" -> "joueurs: Map<String, Joueur>" : clear()

note right of "joueurs: Map<String, Joueur>"
    Selon Expert
end note

@enduml